version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./html_files:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
